"""create set logs table

Revision ID: 432fccfe4f6e
Revises: 6c6f8b7f8c9f
Create Date: 2026-07-08 18:35:14.822287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '432fccfe4f6e'
down_revision: Union[str, Sequence[str], None] = '6c6f8b7f8c9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_logs', sa.Column('planned_weight', sa.Float(), nullable=True))
    op.add_column('set_logs', sa.Column('actual_weight', sa.Float(), nullable=True))
    op.add_column('set_logs', sa.Column('planned_reps', sa.Integer(), nullable=True))
    op.add_column('set_logs', sa.Column('actual_reps', sa.Integer(), nullable=True))
    op.add_column('set_logs', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('set_logs', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('set_logs', 'rir',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               type_=sa.Integer(),
               existing_nullable=True)
    op.drop_column('set_logs', 'reps')
    op.drop_column('set_logs', 'weight')
    op.drop_column('set_logs', 'failed')
    op.drop_column('set_logs', 'duration_seconds')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('set_logs', sa.Column('duration_seconds', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('set_logs', sa.Column('failed', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('set_logs', sa.Column('weight', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.add_column('set_logs', sa.Column('reps', sa.INTEGER(), autoincrement=False, nullable=False))
    op.alter_column('set_logs', 'rir',
               existing_type=sa.Integer(),
               type_=sa.DOUBLE_PRECISION(precision=53),
               existing_nullable=True)
    op.drop_column('set_logs', 'updated_at')
    op.drop_column('set_logs', 'created_at')
    op.drop_column('set_logs', 'actual_reps')
    op.drop_column('set_logs', 'planned_reps')
    op.drop_column('set_logs', 'actual_weight')
    op.drop_column('set_logs', 'planned_weight')
    # ### end Alembic commands ###
